import React from 'react'
import Head from 'next/head'

export default function RegisterPage() {
    return (
        <div className='Register-page'>
            <Head>
                <title>NextJS | Register</title>
                <meta name="description" content="Generated by lamnvt" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                Register Page
            </main>
        </div>
    )
}
