import { useRouter } from 'next/router'
import React from 'react'
import Head from 'next/head'

export default function SlugProfilePage() {
    const slugrouterProfile = useRouter()
    return (
        <div>
            <Head>
                <title>NextJS | Profile Slug</title>
                <meta name="description" content="Generated by lamnvt" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                Profile Page by slug: {slugrouterProfile.query.slugProfile}
            </main>
        </div>
    )
}
