import { useRouter } from 'next/router'
import React from 'react'
import Head from 'next/head'
// rfc
export default function IdProfilePage() {
    const Idrouterprofile = useRouter()
    return (
        <div className='Profile-page'>
            <Head>
                <title>NextJS | Profile Id</title>
                <meta name="description" content="Generated by lamnvt" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                Profile Page {Idrouterprofile.query.profileId}
            </main>
        </div>
    )
}