import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
    return (
        <div className={styles.container}>
            <Head>
                <title>NextJS | Lamnvt</title>
                <meta name="description" content="Generated by lamnvt" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <h1 className={styles.title}>
                    Welcome to <a href="https://nextjs.org">Next.js!</a>
                </h1>
                <p className={styles.description}>
                    Get started by editing{' '}
                    <code className={styles.code}>pages/index.tsx</code>
                </p>
                <div className={styles.grid}>
                    <a href="/users/login" className={styles.card} target="_blank">
                        <h2>Login &rarr;</h2>
                    </a>
                    <a href="/users/register" className={styles.card} target="_blank">
                        <h2>Register &rarr;</h2>
                    </a>
                    <a href="/users/profile/1" className={styles.card} target="_blank">
                      <h2>Profile by id &rarr;</h2>
                    </a>
                    <a href="/users/profile/1/nextjs" className={styles.card} target="_blank">
                        <h2>Profile by slug &rarr;</h2>
                    </a>
                </div>
            </main>
        </div>
    )
}

export default Home
