import React from 'react'
import Head from 'next/head'

export default function LoginPage() {
    return (
        <div className='Login-page'>
            <Head>
                <title>NextJS | Login</title>
                <meta name="description" content="Generated by lamnvt" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                Login Page
            </main>
        </div>
    )
}
